package edu.bhcc;

import jakarta.persistence.*;

/**
 * Customer Plain Old Java Object (POJO).
 * The `Run` class represents a running record. It maps to a "run" table in the database using
 * JPA annotations.
 */
@Entity
@Table(name = "run")
public class Run {

    /**
     * Unique identifier for the run (primary key). Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String route;
    private Double miles;
    private String date;

    /**
     * Protected Constructor, used by JPA.
     */
    protected Run() {
    }

    /**
     * Public Constructor, used to create new Run Objects.
     *
     * @param route The route of the run.
     * @param miles The distance of the run in miles.
     * @param date The date of the run.
     */
    public Run(String route, Double miles, String date) {
        this.route = route;
        this.miles = miles;
        this.date = date;
    }

    /**
     * Gets the unique identifier for the run.
     *
     * @return The ID of the run.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the run. This method should not be called directly
     * as the ID is auto-generated by the database.
     *
     * @param id The ID to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the route of the run.
     *
     * @return The route of the run.
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the route of the run.
     *
     * @param route The route to set.
     */
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * Gets the distance of the run in miles.
     *
     * @return The distance of the run in miles.
     */
    public Double getMiles() {
        return miles;
    }

    /**
     * Sets the distance of the run in miles.
     *
     * @param miles The distance to set.
     */
    public void setMiles(Double miles) {
        this.miles = miles;
    }

    /**
     * Gets the date of the run.
     *
     * @return The date of the run.
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the date of the run.
     *
     * @param date The date to set.
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Returns a string representation of the `Run` object.
     *
     * @return A formatted string containing the run's details.
     */
    @Override
    public String toString() {
        return String.format(
                "Run[id=%d, route='%s', miles='%.2f', date='%s']",
                id, route, miles, date);
    }
}